Repository binbashar/le-dev-makefiles, pull requests merged in 2020-10, with the labels that each got.

#1 Change some of the variables in Release Mgmt makefile to use lazy set…
  release-mgmt/release.mk
Labels: 2020 Q4, bug

#2 BBL-313 | [docker] Build | automation improvement #37
  docker/docker-hub-build-push-single-arg.mk
  docker/docker-hub-build-push-tag-list-single-arg.mk
  docker/docker-hub-build-push-tag-list.mk
  docker/docker-hub-build-push.mk
  helm/helm-k8s-helmsman.mk
  helm/helm-k8s-kubectl.mk
  helm/helm-kind-helmsman.mk
  helm/helm-kind-kubectl.mk
  kubectl/kubectl13.mk
  kubectl/kubectl14.mk
  mkdocs/mkdocs-material.mk
  release-mgmt/release.mk
  terraform11/terraform11-subfolder.mk
  terraform11/terraform11.mk
  terraform12/terraform12-import-rm.mk
  terraform12/terraform12-mfa.mk
  terraform12/terraform12-no-warn.mk
  terraform12/terraform12-root-context.mk
  terraform12/terraform12-subfolder.mk
  terraform12/terraform12.mk
  terraform13/terraform13-import-rm.mk
  terraform13/terraform13.mk
  terratest12/terratest12.mk
  terratest13/terratest13.mk
Labels: 2020 Q4, bug, enhancement

#3 BBL-192 | including base.mk to support custom configs for every makefile
  Makefile
  ansible/ansible-roles.mk
  ansible/ansible.mk
  circleci/circleci.mk
  docker/docker-compose-node.mk
  docker/docker-hub-build-push-single-arg.mk
  docker/docker-hub-build-push-tag-list-single-arg.mk
  docker/docker-hub-build-push-tag-list.mk
  docker/docker-hub-build-push.mk
  git/git.mk
  github/github.mk
  helm/helm-k8s-helmsman.mk
  helm/helm-k8s-kubectl.mk
  helm/helm-kind-helmsman.mk
  helm/helm-kind-kubectl.mk
  kops/kops-extras.mk
  kops/kops.mk
  mkdocs/mkdocs-material.mk
  release-mgmt/release.mk
  terraform11/terraform11-subfolder.mk
  terraform11/terraform11.mk
  terraform12/terraform12-import-rm.mk
  terraform12/terraform12-mfa.mk
  terraform12/terraform12-no-warn.mk
  terraform12/terraform12-root-context.mk
  terraform12/terraform12-subfolder.mk
  terraform12/terraform12.mk
  terraform13/terraform13-import-rm-subfolder.mk
  terraform13/terraform13-import-rm.mk
  terraform13/terraform13-mfa.mk
  terraform13/terraform13-root-context.mk
  terraform13/terraform13-subfolder.mk
  terraform13/terraform13.mk
  terratest12/terratest12.mk
  terratest13/terratest13.mk
  yarn/yarn.mk
Labels: 2020 Q4, enhancement

#4 BBL-192 | adding optional include sintext
  Makefile
  ansible/ansible-roles.mk
  ansible/ansible.mk
  circleci/circleci.mk
  docker/docker-compose-node.mk
  docker/docker-hub-build-push-single-arg.mk
  docker/docker-hub-build-push-tag-list-single-arg.mk
  docker/docker-hub-build-push-tag-list.mk
  docker/docker-hub-build-push.mk
  git/git.mk
  github/github.mk
  helm/helm-k8s-helmsman.mk
  helm/helm-k8s-kubectl.mk
  helm/helm-kind-helmsman.mk
  helm/helm-kind-kubectl.mk
  kops/kops-extras.mk
  kops/kops.mk
  mkdocs/mkdocs-material.mk
  release-mgmt/release.mk
  terraform11/terraform11.mk
  terraform12/terraform12-import-rm.mk
  terraform12/terraform12-mfa.mk
  terraform12/terraform12-no-warn.mk
  terraform12/terraform12-root-context.mk
  terraform12/terraform12.mk
  terraform13/terraform13-import-rm.mk
  terraform13/terraform13-mfa.mk
  terraform13/terraform13-root-context.mk
  terraform13/terraform13.mk
  terratest12/terratest12.mk
  terratest13/terratest13.mk
  yarn/yarn.mk
Labels: 2020 Q4, bug

#7 BBL-192 | adding auto make decrypt validation to make apply, plan and destroy
  terraform11/terraform11-subfolder.mk
  terraform11/terraform11.mk
  terraform12/terraform12-subfolder.mk
  terraform12/terraform12.mk
  terraform13/terraform13-subfolder.mk
  terraform13/terraform13.mk
Labels: 2020 Q4, enhancement
